### ISSUE TITLE
Receiving empty new tweet "None" from Stream

### ISSUE THREAD

**Issue by gschurck** [sns-sdks/python-twitter#109]
First thanks for this lib it's the easiest I found to manage Twitter Stream.
I have a strict Stream filter rule on my account, but I receive new tweet signals with empty tweet multiple times a day (tweet=None) from Stream, as there are no now tweets corresponding to this filter (I checked carefully).
Is it a normal behavior ? Or it can a bug from Twitter or the lib ?
Thanks.

**Comment by MerleLiuKun** [comment]
Yes, stream in library only return the data. And not handle the data, Maybe you need filter the `None` data.

**Comment by gschurck** [comment]
Okay thanks, so strange behavior from twitter data.
