### ISSUE TITLE
No `media_fields` parameter in `get_list_tweets`

### ISSUE THREAD

**Issue by Dhravya** [sns-sdks/python-twitter#117]
I was trying to get all the images from a twitter list.

But noticed that there is no `media_fields` parameter in get_list_tweets

Any particular reason for this? if not, can someone please add it as soon as possible?

```py
    tweets = api.get_list_tweets(
        list_id="1546525780347604992",
        tweet_fields=["created_at"],
        user_fields=[
            "username",
            "name",
            "profile_image_url",
            "created_at",
        ],  # To get the username
        expansions=["attachments.media_keys", "author_id"],
        media_fields=["preview_image_url", "url"], 
        return_json=True,
    )
    ```

**Comment by Dhravya** [comment]
Just went through the twitter docs and found that there is no `media_fields` keyword for this endpoint.

Is it possible to get the URL of an image using the media key?

**Comment by MerleLiuKun** [comment]
I just tried this endpoint, and found, this can support for `media_fields`, but the docs not point it, So api may need update.

**Comment by MerleLiuKun** [comment]
Maybe the docs is missing.
