### ISSUE TITLE
`create_tweet` is throwing Connection Error

### ISSUE THREAD

**Issue by KunalSin9h** [sns-sdks/python-twitter#123]
I am not able to tweet.
I have a script ([main.py](https://github.com/KunalSin9h/Gita-Verse/blob/master/main.py)) to tweet 3 times a day and after tweeting single time `api.create_tweet` throw `ConnectionError`.

![Screenshot from 2022-10-12 14-11-21](https://user-images.githubusercontent.com/82411321/195295326-6bb94c43-c4b8-47eb-b84d-6b3e70e43726.png)

**Comment by MerleLiuKun** [comment]
You may check the network to connect the twitter services.:)

**Comment by KunalSin9h** [comment]
you mean internet ?

**Comment by MerleLiuKun** [comment]
yes, you can check it.

**Comment by KunalSin9h** [comment]
it is running on Azure.
i have fix this by re trying to tweet when it throws error.
see.
```py
        try:
            api.create_tweet(text=hero_text)
        except:
            print(f"on verse: {current_verse_id} at  create_tweet something went wrong, Retrying again...   -    {time.strftime('%X %x %Z')}")
            try:
                api.create_tweet(text=hero_text)
            except:
                print(f"Fail again!  - {time.strftime('%X %x %Z')}")
            else:
                print(f"Tweet Send on second try for verse {current_verse_id}   -    {time.strftime('%X %x %Z')}")
        else:
            print(f"Tweet Send for verse {current_verse_id}   -   {time.strftime('%X %x %Z')}")
```

it works on trying again just after exception.

**Comment by MerleLiuKun** [comment]
I have test some tweets, and not found this issue, I guess there may have some connection errors on the vm. :)

**Comment by QuiTran86** [comment]
You shouldn't wrap the exception to the specific string like:
except: print... when you not sure what is the type of that exception. In this case, you should raise the full exception and bring it on here, so others can help you if they can.
