### ISSUE TITLE
Question/Possible argument bug in api.create_tweet()

### ISSUE THREAD

**Issue by WorldofHackercraft** [sns-sdks/python-twitter#135]
Hi, this is something I probably should've reported a while ago, but I couldn't access my github account.  
I don't have the exact error reproduced, but it should be easy to do.  It involves calling api.create_tweet like so:
`api.create_tweet(text="some text", reply_in_reply_to_tweet_id="12345")`
My use case is simply replying to another user's tweet.  
You would think this would be common enough that if this issue existed other people would've mentioned or fixed it by now.  

Anyways, an exception was thrown and based on the error message I discerned that something was wrong with the "reply_exclude_reply_user_ids" parameter.  

So I fixed the problem with a little guesswork by changing my call thusly:
`api.create_tweet(text="some text", reply_in_reply_to_tweet_id="12345", reply_exclude_reply_user_ids=[])`
An empty list seems to be acceptable for whatever reason, at least for "reply_exclude_reply_user_ids." Maybe that would make a better default value?

It looks like for whatever reason, the default value of this parameter is None, and when you specify a "reply_in_reply_to_tweet_id" arg, it automatically adds the "reply_exclude_reply_user_ids" arg into its "args[reply]" dictionary key as it builds the api/http request.  I'm looking at lines 605-612 in file "api.py."  
By only using one of these two arguments, you're unwittingly adding the default value of the other to your api request.  

Maybe this is documented somewhere, but I couldn't find it in the docs that you were required to specify an empty array if defining one of the args but not the other?  But if you don't do this, it fudges up the api request and causes an error/exception.  

Sorry if this has been resolved already and discussed.
I'm only hoping to help others who might encounter this issue and get stuck on it.  Thank you!

**Comment by MerleLiuKun** [comment]
Yes, I have reproduced this error,  I will fix it quickly.!
