### ISSUE TITLE
Rate limiting not looking at correct resource/endpoint

### ISSUE THREAD

**Issue by BradWaite** [sns-sdks/python-twitter#141]
When calling `/users/by/username` with multiple usernames, the limits are set for the full URL (e.g. `/users/by/username/x`, not the endpoint (`/users/by/username`), so subsequent calls see the default 900 calls remaining and carry on until Twitter responds with 'Too Many Requests'.

With this particular endpoint, stripping out the username from the URL in `url_to_endpoint()` resolves the issue, but I'm unsure whether it will break other endpoints:
```
	def url_to_endpoint(url) -> Endpoint:
		resource = urlparse(url).path.replace("/2", "", 1)  # only replace api version
		resource = resource[:resource.rfind('/')]
		for endpoint in PATH_VAR_ENDPOINTS:
			if re.fullmatch(endpoint.regex, resource):
				return endpoint
		return Endpoint(resource=resource)
```

**Comment by MerleLiuKun** [comment]
oh i will check this and fix it.
