### ISSUE TITLE
missing "url" field in the "Media" model

### ISSUE THREAD

**Issue by tomachalek** [sns-sdks/python-twitter#45]
Hello, it looks like the `url` field is missing from the `Media` model. The field is described on a respective [Twitter API docs page](https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent) (chapter "Query parameters", `media.fields`).

I don't know all the intricacies of the API, but it seems that the field is empty in case of some media (e.g. an animated GIF from the tweet you use in your tests). But when dealing e.g. with an attached picture, the field is non-empty. Interestingly, the `preview_image_url` seems to be missing in such case (at least for tweets I've been dealing with).

**Comment by MerleLiuKun** [comment]
Hey, the field `preview_image_url` only for the `video` media.  

The field `url` is missing, I have add it. this is strange design. When media  is `photo`, `url` will return, when media is `video` or `animated_gif` , `preview_image_url` will return for the video preview image.
