### ISSUE TITLE
Long running stream crashes in streaming.py

### ISSUE THREAD

**Issue by SimonShapiro** [sns-sdks/python-twitter#70]
I have a very long running twitter stream monitor running in a Linode server.  There was some unusual behaviour, which I have now traced to the following error message:

```
Exception in request, exc: 'data'
Traceback (most recent call last):
  File "/root/twitter-stream/python37/lib/python3.7/site-packages/pytwitter/streaming.py", line 107, in _connect
    self.on_data(raw_data=line, return_json=return_json)
  File "/root/twitter-stream/python37/lib/python3.7/site-packages/pytwitter/streaming.py", line 140, in on_data
    data = md.Tweet.new_from_json_dict(data=data["data"])
KeyError: 'data'

```
This is tricky for me to analyse as it happens during filtered streaming and so can't be easily reproduced.  I would say though that is at least once a day.  All I can do is restart the stream and hope for the best at this stage.

Any ideas or information on how to trap it or give you more info to go will?

**Comment by MerleLiuKun** [comment]
Yes, I have got this. 

I will quick make a new release to solve it.

**Comment by MerleLiuKun** [comment]
Sometime twitter will not return data, So in this case, will return no data.

**Comment by MerleLiuKun** [comment]
Hey! 

I have make a new release, You can try it. Let me know if appear something.:)
